import os
import json
import hashlib
import hmac
from typing import Optional
import click

try:
    from PyPDF2 import PdfReader
except Exception:
    PdfReader = None


def _generate_hmac(data: dict, secret: Optional[str] = None) -> str:
    if secret is None:
        secret = os.getenv("CERT_SECRET", "default-secret")
    s = json.dumps(data, sort_keys=True)
    return hmac.new(secret.encode(), s.encode(), hashlib.sha256).hexdigest()


def generate_checksum(cert_record: dict, secret: Optional[str] = None) -> str:
    """
    Must match HiddenMetadata.generate_checksum(cert_data) in generator.
    """
    core = {
        "certificate_id": cert_record["certificate_id"],
        "recipient_name": cert_record["recipient_name"],
        "issue_date": cert_record["issue_date"],
        "issuer": cert_record["issuer"],
        "title": cert_record["title"],
        "generated_at": cert_record["generated_at"],
    }
    full = _generate_hmac(core, secret)
    return full[:16]


def generate_signature(cert_record: dict, token_hash: str, secret: Optional[str] = None) -> str:
    """
    Must match HiddenMetadata.generate_signature(cert_data, token_hash) in generator.
    """
    core = {
        "certificate_id": cert_record["certificate_id"],
        "recipient_name": cert_record["recipient_name"],
        "issue_date": cert_record["issue_date"],
        "issuer": cert_record["issuer"],
        "title": cert_record["title"],
        "generated_at": cert_record["generated_at"],
        "token_hash": token_hash,
    }
    return _generate_hmac(core, secret)


def extract_payload_from_pdf(pdf_path: str):
    if PdfReader is None:
        raise RuntimeError("PyPDF2 is not installed. Install with: pip install PyPDF2")

    reader = PdfReader(pdf_path)
    info = reader.metadata or {}

    for v in info.values():
        if isinstance(v, str) and "CertGen|" in v:
            raw = v.split("CertGen|", 1)[1]
            return json.loads(raw)

    return None


def load_local_record(cert_id: str):
    from pathlib import Path
    p = Path("credentials.json")
    if not p.exists():
        return None

    with p.open("r", encoding="utf-8") as f:
        records = json.load(f)

    return next((r for r in records if r.get("certificate_id") == cert_id), None)


@click.group()
def cli():
    """Certificate verification CLI (PDF-only, hidden metadata)."""
    pass


@cli.command("verify-file")
@click.option("--file", "file_path", required=True, type=click.Path(exists=True),
              help="Certificate PDF file to verify")
def verify_file(file_path: str):

    payload = extract_payload_from_pdf(file_path)
    if not payload:
        click.secho("✗ No embedded certificate metadata found in PDF", fg="red")
        click.echo("  (The file may not have been generated by this system.)")
        return

    cert_id = payload.get("id")
    embedded_token_hash = payload.get("token_hash")
    embedded_checksum = payload.get("checksum")
    embedded_signature = payload.get("signature")
    has_qr = payload.get("has_qr", False)

    if not cert_id or not embedded_token_hash or not embedded_checksum:
        click.secho("✗ Embedded metadata incomplete", fg="red")
        return

    record = load_local_record(cert_id)
    if not record:
        click.secho("✗ Certificate not found in credentials.json", fg="red")
        return

    stored_creds = record.get("credentials", {}) or {}
    stored_token_hash = stored_creds.get("token_hash")
    stored_checksum = stored_creds.get("checksum")
    stored_signature = stored_creds.get("signature")

    # 1) token hash must match
    if stored_token_hash != embedded_token_hash:
        click.secho("✗ Token hash mismatch – certificate is not authentic", fg="red")
        return

    # 2) checksum must match both embedded & stored
    expected_checksum = generate_checksum(record)
    if embedded_checksum != expected_checksum or stored_checksum != expected_checksum:
        click.secho("✗ Checksum mismatch – PDF or record tampered", fg="red")
        return

    # 3) digital signature must match (if present)
    if embedded_signature:
        expected_signature = generate_signature(record, stored_token_hash)
        if embedded_signature != expected_signature or (stored_signature and stored_signature != expected_signature):
            click.secho("✗ Digital signature mismatch", fg="red")
            return

    click.secho("✓ Certificate VERIFIED", fg="green")
    click.echo(f"  Certificate ID : {cert_id}")
    click.echo(f"  Recipient      : {record['recipient_name']}")
    click.echo(f"  Issue Date     : {record['issue_date']}")
    click.echo(f"  Issuer         : {record['issuer']}")
    click.echo(f"  QR Code        : {'PRESENT' if has_qr else 'MISSING / NOT EMBEDDED'}")
    click.echo(f"  Digital Sign.  : {'VALID' if embedded_signature else 'NOT PRESENT'}")


if __name__ == "__main__":
    cli()
