"""
Standalone Certificate Verification Tool
Verification is based ONLY on:
  - Certificate ID
  - Token

Usage:
  python verify_tool.py verify --cert-id CERT-XXXX --token "<TOKEN>"

This tool verifies against the local credentials.json file
generated by certificate_generator.py.
"""

import os
import json
import hashlib
import hmac
from typing import Optional

import click


# ========================= Checksum Helper =========================

def generate_checksum(data: dict, secret: Optional[str] = None) -> str:
    if secret is None:
        secret = os.getenv("CERT_SECRET", "default-secret")
    s = json.dumps(data, sort_keys=True)
    return hmac.new(secret.encode(), s.encode(), hashlib.sha256).hexdigest()[:16]


# ========================= Local Store Helper =========================

def load_local_record(cert_id: str) -> Optional[dict]:
    from pathlib import Path
    local_file = Path("credentials.json")

    if not local_file.exists():
        return None

    try:
        with local_file.open("r", encoding="utf-8") as f:
            records = json.load(f)
        return next((r for r in records if r.get("certificate_id") == cert_id), None)
    except Exception:
        return None


# ========================= CLI =========================

@click.group()
def cli():
    """Certificate Verification Tool (Certificate ID + Token ONLY)"""
    pass


@cli.command("verify")
@click.option("--cert-id", required=True, help="Certificate ID")
@click.option("--token", required=True, help="Verification Token")
def verify(cert_id: str, token: str):
    """
    Verify a certificate using ONLY:
      - Certificate ID
      - Token
    """
    record = load_local_record(cert_id)

    if not record:
        click.secho("✗ Certificate ID not found", fg="red")
        return

    token_hash_local = hashlib.sha256(token.encode()).hexdigest()
    stored_hash = record.get("credentials", {}).get("token_hash")

    if token_hash_local != stored_hash:
        click.secho("✗ Token mismatch – certificate NOT valid", fg="red")
        return

    recompute = {
        "certificate_id": record.get("certificate_id"),
        "recipient_name": record.get("recipient_name"),
        "issue_date": record.get("issue_date"),
        "issuer": record.get("issuer"),
        "title": record.get("title"),
        "generated_at": record.get("generated_at"),
    }

    expected = generate_checksum(recompute)
    stored = record.get("credentials", {}).get("checksum")

    if expected != stored:
        click.secho("✗ Certificate data tampered", fg="red")
        return

    # ✅ VERIFIED
    click.secho("✓ Certificate VERIFIED", fg="green")
    click.echo(f"  Certificate ID : {cert_id}")
    click.echo(f"  Recipient      : {record.get('recipient_name')}")
    click.echo(f"  Issue Date     : {record.get('issue_date')}")

    device = record.get("device_info") or {}
    if device:
        os_name = device.get("Operating System") or device.get("os") or "N/A"
        click.echo("  Device Info:")
        click.echo(f"    OS              : {os_name}")
        click.echo(f"    Device ID       : {device.get('device_id', 'N/A')}")
        click.echo(f"    Space Recovered : {device.get('size_removed', 'N/A')}")
        click.echo(f"    Action Type     : {device.get('action_type', 'N/A')}")
        click.echo(f"    Timestamp       : {device.get('timestamp', 'N/A')}")


if __name__ == "__main__":
    cli()
